package com.sample
 
import org.lyh.sample.test.DroolsTest.Message;

rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message );
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message );
    then
        System.out.println( myMessage );
end

function String hello(String name) {
	return "Hello " + name;
}

rule "Hello World 1"
    when
        m:Message( owners contains owner );
    then
        System.out.println( m.getOwner().getName() );
end
